# Generated by Django 5.2.4 on 2025-08-07 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('attributes', models.JSONField(blank=True, null=True)),
                ('monthly_sales', models.JSONField(blank=True, null=True)),
                ('segment_share', models.JSONField(blank=True, null=True)),
                ('seasonal_trend', models.TextField(blank=True)),
                ('promotion_effect', models.FloatField(blank=True, null=True)),
                ('summary', models.TextField()),
            ],
            options={
                'verbose_name_plural': '참조 제품',
            },
        ),
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('persona_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.persona')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatthread')),
            ],
        ),
    ]
