# Generated by Django 5.2.4 on 2025-08-27 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_alter_chatthread_id"),
        (
            "persona",
            "0003_alter_persona_age_group_alter_persona_customer_value_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatthread",
            name="persona_id",
        ),
        migrations.AddField(
            model_name="chatthread",
            name="persona",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="persona.persona",
            ),
        ),
    ]
