# Generated by Django 5.2.4 on 2025-08-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('segment', models.CharField(max_length=50)),
                ('age_group', models.CharField(max_length=10)),
                ('family_structure', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('customer_value', models.CharField(max_length=50)),
                ('purchase_pattern', models.JSONField(max_length=100)),
                ('lifestyle', models.JSONField(max_length=100)),
                ('job', models.CharField(max_length=50)),
                ('persona_summary_tag', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name_plural': '페르소나',
            },
        ),
    ]
