# Generated by Django 5.2.4 on 2025-08-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='age_group',
            field=models.CharField(help_text='예: 30대', max_length=10),
        ),
        migrations.AlterField(
            model_name='persona',
            name='customer_value',
            field=models.CharField(help_text='예: 웰빙형', max_length=50),
        ),
        migrations.AlterField(
            model_name='persona',
            name='family_structure',
            field=models.CharField(help_text='예: 1인 가구', max_length=50),
        ),
        migrations.AlterField(
            model_name='persona',
            name='gender',
            field=models.CharField(help_text='예: 여성', max_length=10),
        ),
        migrations.AlterField(
            model_name='persona',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='job',
            field=models.CharField(help_text='예: 직장인', max_length=50),
        ),
        migrations.AlterField(
            model_name='persona',
            name='lifestyle',
            field=models.JSONField(help_text='예: 액티브', max_length=100),
        ),
        migrations.AlterField(
            model_name='persona',
            name='persona_summary_tag',
            field=models.TextField(help_text='예: 30대 여성, 웰빙형', max_length=500),
        ),
        migrations.AlterField(
            model_name='persona',
            name='purchase_pattern',
            field=models.JSONField(help_text='예: 온라인 쇼핑 선호', max_length=100),
        ),
    ]
