# Generated by Django 5.2.4 on 2025-08-08 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_alter_persona_age_group_alter_persona_customer_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='age_group',
            field=models.CharField(help_text='예: 40대', max_length=10),
        ),
        migrations.AlterField(
            model_name='persona',
            name='customer_value',
            field=models.CharField(help_text='예: VIP', max_length=50),
        ),
        migrations.AlterField(
            model_name='persona',
            name='family_structure',
            field=models.CharField(help_text='예: 부부', max_length=50),
        ),
        migrations.AlterField(
            model_name='persona',
            name='gender',
            field=models.CharField(help_text='예: 여', max_length=10),
        ),
        migrations.AlterField(
            model_name='persona',
            name='job',
            field=models.CharField(help_text='예: 은퇴자', max_length=50),
        ),
        migrations.AlterField(
            model_name='persona',
            name='lifestyle',
            field=models.JSONField(help_text='예: 웰빙추구형, 트렌드추종형', max_length=100),
        ),
        migrations.AlterField(
            model_name='persona',
            name='persona_summary_tag',
            field=models.TextField(help_text='예: 40대 여, 은퇴자, 부부, 우수고객, 유제품, 통조림/즉석/면류, 웰빙추구형, 트렌드추종형', max_length=500),
        ),
        migrations.AlterField(
            model_name='persona',
            name='purchase_pattern',
            field=models.JSONField(help_text='예: 유제품, 통조림/즉석/면류', max_length=100),
        ),
        migrations.AlterField(
            model_name='persona',
            name='segment',
            field=models.CharField(help_text='예: 웰빙추구형 VIP', max_length=50),
        ),
    ]
