# Generated by Django 5.2.4 on 2025-08-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_alter_persona_age_group_alter_persona_customer_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='age_group',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='family_structure',
            new_name='household',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='customer_value',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='lifestyle',
        ),
        migrations.AddField(
            model_name='persona',
            name='education',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='income_month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='income_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='marriage',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='segment_decription',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='persona_summary_tag',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='persona',
            name='purchase_pattern',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
