# Generated by Django 5.2.4 on 2025-08-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_rename_age_group_persona_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='region',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
